sudo: required
language: node_js
node_js:
- '7'
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.23.2
- export PATH="$HOME/.yarn/bin:$PATH"
- docker build -t $DOCKER_REPO .
- docker run -p 5000:5000 -d $DOCKER_REPO
- docker ps -a
cache: yarn
script:
- yarn flow
- yarn lint
- yarn docs
- yarn test
- yarn report-coverage
- yarn prod
- yarn pa11y
- yarn firebase-deploy
services:
- docker
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
- test "$TRAVIS_BRANCH" = "master" && docker push $DOCKER_REPO;
- test "$TRAVIS_BRANCH" = "master" && sh deploy_heroku.sh
notifications:
  slack:
    secure: D6McHobrLhQY4EXdTRrw/BJX03ULgpRpWDlj3QgiZ8ufTiOG0bmJ3LKe9YpYUa4c44g9Kbyr51azXSGdR+d5etRm94FwEi2DLpejVyVPyVirRSDiK+kuNnl0GLJFB2H1ZSUZq5TadDNhY0Cc/75CmynYHKeXOSpm+CfUnTe4LH0PZf1iAxESZoivV/zj8G9mBeB/9nbzHpREicpl/Tcfltc60FL3siXORo4UxmCUstYBrRIAuFuhfKCS3DOyZcvBWeEFQroGpqKbKHDw+P4qyCC5lxDWeU6RcIcUZiscsGyS56uJVAOayGzdHi0d40etd/9vQSF5ZbbrDNQDYeCODkIJUTuaOwtkUjHGLvTmQpv0x7vJ6kmcsh/slIgaQxvfsAE19TGAm/IWrNw59iVz9mO5dAhOOdVgXhk52EU8z1o7mmte43e7FNPXdOb1ywanzS7+Du2uKBbFLOmQUMe0ixi9AWIMtVFUAxj6JJNaMksjQjejX9INCYozc82DOpRSUQlBlcXpoh+PlfCgo0p76GQK0r0xUiDlvQ0816EFJX7pHNZmhW1JC6MD3EAYRW2Rueghd+T9fJVDVJ/HXcNlZ2gqa9v9X4N5bL1oBoOJeA68IktWG1f64eivwX5hzaRUJ5/QbEeV+PpfrT3rN4ZOpy56cZhn7i+Jvm/wLwfF/nM=
