sudo: required
language: node_js
node_js:
- '7'
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.23.2
- export PATH="$HOME/.yarn/bin:$PATH"
- docker build -t $DOCKER_REPO .
- docker run -p 5000:5000 -d $DOCKER_REPO
- docker ps -a
cache: yarn
script:
- yarn flow
- yarn lint
- yarn docs
- yarn test
- yarn report-coverage
- yarn prod
- yarn pa11y
- yarn firebase-deploy
services:
- docker
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
- test "$TRAVIS_BRANCH" = "master" && docker push $DOCKER_REPO;
- test "$TRAVIS_BRANCH" = "master" && sh deploy_heroku.sh
notifications:
  slack:
    rooms:
      secure: pCl2f2HDrE3SSjjcXhETg762ygCVGll+2e9UA0mLFQC7dr2d0nxvDkUXF4c4cqeAw59vAjBkPYej+d5A8pY0ofMEqs4etHQr/8yUNQ+ilhMhh+u/edePfLFkP8Cjf1n7fy3JwzIiXb5wRdD1L7S/c40QCxIY06scxELsVLKCz/+NEb1NKZPClUM01DQzVPXKj7ICVKrgnx4cqzQTKcgo5vEd1K6pBfGlkXtmxEJHDUUu/u6Jz79uIanW9S5grZ3I/emMLm/nRRg0L/2bZrMIBg49FWVH2uojmhYBLRP1cEbencBZUXS6hf0an7lBJC2f2DGNwTaBT2P/uQ6giIfJgIzbzBtgdvSjS73QQwZP/qRpPlvt4zDFuYR64vS0UWTpb/RQstv8nT6zTpkSWWjWwqAc57tXE+HCSBTAlXR+Cde0wvU/xJ6Hj1DWLGJv0q5IXO8pZY38QUbqBn26dxTpMEYHrpIXq7jZ25Q18BV5UETYG2KDNJDgLyd9NTZ1/n9J46MCK3DPkSq397D7kQ/50awwzxHnNix5ouOgvTcUT7eJdOwgBkO3Y5y7m36fuvl3/tegZEQmXd5CZTkjiPRCxvvpmL0v8B9z1qd+77kMtN/x8Hg7lsq0D7jdGV6lKg25hSVXQnmU1vDFWN7YvxhKGbg0eg4hC5c4ctAerFmLsoY=
