sudo: required
language: node_js
node_js:
- '7'
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.23.2
- export PATH="$HOME/.yarn/bin:$PATH"
- docker build -t $DOCKER_REPO .
- docker run -p 5000:5000 -d $DOCKER_REPO
- docker ps -a
services:
- docker
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
- docker push $DOCKER_REPO;
- test "$TRAVIS_BRANCH" = "master" && sh deploy_heroku.sh