sudo: required
language: node_js
node_js:
- '7'
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.23.2
- export PATH="$HOME/.yarn/bin:$PATH"
- docker build -t sreeram/pipeline .
- docker run -p 5000:5000 -d sreeram/pipeline
- docker ps -a
cache: yarn
services:
- docker
script:
- yarn travis
- docker ps
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
- docker push sreeram/pipeline;
- test "$TRAVIS_BRANCH" = "master" && sh deploy_heroku.sh