language: node_js
node_js:
- '7'
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.23.2
- export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
script:
- yarn travis
deploy:
  provider: firebase
  token:
    secure: C5NlmBeC5BfOfFFPO64hR3Ugww0t511itEnSgSSOTKDH1qY+Y/KZX0OOkTloNzPctyvqewW3IGG1NHAcJxKJYU28++EFsG4DMrKo/Feuy9NvZ0Lq/m/coN/0pmKzFN2jT8OaAouuA9Yaa8bx53MzPH91SOxuI7qWo1CvCEaWhZPRisBzfG95t8Zyw86YCa290xEraic+n1Xyc7xr0Wc/3km7kHNaw2zU6JgZDuJO2YXK0v1caCKqXEVFEaOoxc72KifkYI8Ak/Usy5RTLe/Z1ojlmrQAdayD+bIpE29HEiseUcAn9J7r+pWh4yQ3VZrYh5RnI8cw1u2M3YIYMUl3G0+pAnhpGrE7CeZ1he0wuNhRUC735+Zu5wy42E71wvoOCInosVg3CMFdB35WADXrKxzlQBWzpjf10a+cgxF5ipAOEaoTAaJcbCmacoH4mPCqfzTFGqnLIalFLBP4dM0YO9CVx53w6vi4tls0hEiof8EGkhAF+rrJsCc0vPMQTWnEODyuzp/c6ed7SAX8thrcuvggrcXMln3p/cOhIIwEptjnxHgRHWikKkktA4KcJUTXX9ISFnLn66Cz3guCTL9+LUbx3XowzRfpPPk1SF47aoQN8lNadsVka7cv97aOIVxsKrlcPqCCWLDDACqaX4hImjRBSEMCIrYmdQXS2pZB8go=
  project: 'ecmascrypt'
env:
  global:
    secure: C5NlmBeC5BfOfFFPO64hR3Ugww0t511itEnSgSSOTKDH1qY+Y/KZX0OOkTloNzPctyvqewW3IGG1NHAcJxKJYU28++EFsG4DMrKo/Feuy9NvZ0Lq/m/coN/0pmKzFN2jT8OaAouuA9Yaa8bx53MzPH91SOxuI7qWo1CvCEaWhZPRisBzfG95t8Zyw86YCa290xEraic+n1Xyc7xr0Wc/3km7kHNaw2zU6JgZDuJO2YXK0v1caCKqXEVFEaOoxc72KifkYI8Ak/Usy5RTLe/Z1ojlmrQAdayD+bIpE29HEiseUcAn9J7r+pWh4yQ3VZrYh5RnI8cw1u2M3YIYMUl3G0+pAnhpGrE7CeZ1he0wuNhRUC735+Zu5wy42E71wvoOCInosVg3CMFdB35WADXrKxzlQBWzpjf10a+cgxF5ipAOEaoTAaJcbCmacoH4mPCqfzTFGqnLIalFLBP4dM0YO9CVx53w6vi4tls0hEiof8EGkhAF+rrJsCc0vPMQTWnEODyuzp/c6ed7SAX8thrcuvggrcXMln3p/cOhIIwEptjnxHgRHWikKkktA4KcJUTXX9ISFnLn66Cz3guCTL9+LUbx3XowzRfpPPk1SF47aoQN8lNadsVka7cv97aOIVxsKrlcPqCCWLDDACqaX4hImjRBSEMCIrYmdQXS2pZB8go=
